export const FETCH_TODO = 'FETCH_TODO'
export const COMPLETED_TODO = 'COMPLETED_TODO'
export const DELETE_TODO = 'REMOVE_TODO'
export const ADD_TODO = 'ADD-TODO'
export const SET_FILTER = 'SET_FILTER'
export const UPDATE_TODO = 'UPDATE_TODO'